apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simplestaticapp
  name: simplestaticapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simplestaticapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simplestaticapp
    spec:
      containers:
      - image: ebenezermakinde/simplestaticapp:4
        name: simplestaticapp
        ports:
        - containerPort: 3500
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 3500
    targetPort: 3500
  selector:
    app: simplestaticapp