apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simplestaticapp
  name: simplestaticapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simplestaticapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simplestaticapp
    spec:
      containers:
      - image: ebenezermakinde/simplestaticapp:1
        name: simplestaticapp
        ports:
        - containerPort: 80
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: simplestaticapp